runtime: java11
entrypoint: java -Xmx256m -jar leap-consent-testing-service/target/consent-testing-service-1.0.0.jar
env_variables:
  CDS_HOST_URL: __CDS_HOST_URL
resources:
  cpu: 1
  memory_gb: 2.0
instance_class: B4_1G
manual_scaling:
  instances: 1
