steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s/__CDS_HOST_URL/${_CDS_HOST_URL}/g" app.yaml && gcloud app deploy app.yaml
